global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
    - targets:
        - "localhost:9090"



- job_name: 'static'
  scrape_interval: 30m
  static_configs: ## CIDR 不支持
    - targets: ["192.168.5.102"]  # switchs
  metrics_path: /snmp
  params:
    auth: []
    module: [if_mib, system]
  relabel_configs: # exporter config relabel 
    - source_labels: [__address__]   
      target_label: __param_target    # snmp_exporter ip -> switch ip
    - source_labels: [__param_target] # switch ip -> instance
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter:9116

- job_name: 'dynamic'
  scrape_interval: 10s
  static_configs:
    - targets: ["192.168.5.102"]  # switch
  metrics_path: /snmp
  params:
    auth: []
    module: [if_mib_dynamic]
  relabel_configs:
    - source_labels: [__address__]    # exporter variable relabel 
      target_label: __param_target    # snmp_exporter ip -> switch ip
    - source_labels: [__param_target] # switch ip -> instance
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter:9116
